function LinksGrabber(k){var l=document,t=k==document?document.scrollingElement:k,u=function(a,d){var b=a.getBoundingClientRect();return{top:Math.round(b.top+(window.pageYOffset||t.scrollTop)),left:Math.round(b.left+(window.pageXOffset||t.scrollLeft)),width:b.width,height:b.height}};return{collectedLinks:[],markHiddenLinks:function(){for(var a=[],d=l.createNodeIterator(k,NodeFilter.SHOW_ELEMENT,null,!1),b;b=d.nextNode();)if(b.childElementCount&&"HTML"!==b.tagName&&b!==k&&(b.offsetHeight<b.scrollHeight||
b.offsetWidth<b.scrollWidth)){var f=l.defaultView.getComputedStyle(b,"");!f||"none"===f.getPropertyValue("display")||"hidden"!==f.getPropertyValue("overflow")&&"hidden"!==f.getPropertyValue("overflow-y")&&"auto"!==f.getPropertyValue("overflow-y")&&"scroll"!=f.getPropertyValue("overflow-y")&&"hidden"!==f.getPropertyValue("overflow-x")&&"auto"!==f.getPropertyValue("overflow-x")&&"scroll"!=f.getPropertyValue("overflow-x")||a.push(b)}a.forEach(function(a){var b=u(a,k);a=a.getElementsByTagName("a");for(var d=
0,e=0;e<a.length;++e){var n=a[e],p=u(n,k);rectsIntersected(b,p)||(n.setAttribute("__fireshotHiddenLink",1),++d)}})},createLinksSnapshot:function(){function a(a){if(a.getAttribute("__fireshotHiddenLink"))return!1;var b=a.href;if(b=b&&""!==b&&"javascript:void(0)"!==b&&b.slice&&"#"!==b.slice(-1)){a:{for(;a&&a!=l;){b=l.defaultView.getComputedStyle(a,"");if("hidden"===b.visibility||"none"===b.display||0==b.opacity){a=!0;break a}a=a.parentNode}a=!1}b=!a}return b}function d(a,b){var e=u(a,k),c=a.getClientRects(),
d=void 0;if(1===c.length){var g;if(c=a.children&&0<a.children.length&&"IMG"===a.children[0].tagName)c=l.defaultView.getComputedStyle(a,""),c=!c||"hidden"!==c.getPropertyValue("overflow")&&"hidden"!==c.getPropertyValue("overflow-y")&&"auto"!==c.getPropertyValue("overflow-y")&&"scroll"!=c.getPropertyValue("overflow-y")&&"hidden"!==c.getPropertyValue("overflow-x")&&"auto"!==c.getPropertyValue("overflow-x")&&"scroll"!=c.getPropertyValue("overflow-x")?u(a.children[0],k):void 0,c=g=c;c?b.push(g):b.push(e)}else{for(g=
0;g<c.length;++g)0===g?d={left:c[g].left,top:c[g].top}:(c[g].left<d.left&&(d.left=c[g].left),c[g].top<d.top&&(d.top=c[g].top));if(d){var f=e.left-d.left,e=e.top-d.top;for(g=0;g<c.length;++g)b.push({left:c[g].left+f,top:c[g].top+e,width:c[g].width,height:c[g].height})}}}for(var b=k.getElementsByTagName("a"),f={left:0,top:0,width:window.innerWidth,height:window.innerHeight},e=0;e<b.length;++e){var h=b[e];if(a(h)){var r=h.getBoundingClientRect();if(rectsIntersected(r,f)&&(r=[],d(h,r),0!==r.length)){var m=
h.getAttribute("__fireshotLinkId");m?m=parseInt(m):(m=this.collectedLinks.length,h.setAttribute("__fireshotLinkId",m));this.collectedLinks[m]={e:h,r:r}}}}},getLinks:function(a,d){var b=a.crop?a.cropRight-a.cropLeft:a.width,f=a.crop?a.cropBottom-a.cropTop:a.height;a.links=[];for(var e=0;e<this.collectedLinks.length;++e){var h=this.collectedLinks[e],k=this.collectedLinks[e].e;if(!k.getAttribute("__fireshotHiddenLink")){for(var m=[],n=0;n<h.r.length;++n){var p=h.r[n].left-d.x,q=h.r[n].top-d.y,c=h.r[n].width,
l=h.r[n].height;p>=b||q>=f||(0>p&&(c+=p,p=0),0>q&&(l+=q,q=0),p+c>b&&(c=b-p),q+l>f&&(l=f-q),0<c&&0<l&&m.push([Math.round(p*a.ratioW),Math.round(q*a.ratioH),Math.round(c*a.ratioW),Math.round(l*a.ratioH)]))}0<m.length&&a.links.push({a:k.href,r:m,h:""})}}getConsolePtr()("links filtered: "+(this.collectedLinks.length-a.links.length));getConsolePtr()("links added: "+a.links.length)},checkClickableLinks:function(){for(var a,d,b=t.scrollLeft,f=t.scrollTop,e=0;e<this.collectedLinks.length;++e)if(!this.collectedLinks[e].p){a=
this.collectedLinks[e].r[0].left-b;d=this.collectedLinks[e].r[0].top-f;0>a&&(a+=this.collectedLinks[e].r[0].width);0>d&&(d+=this.collectedLinks[e].r[0].height);var h;0<=d&&d<=window.innerHeight&&0<=a&&a<=window.innerWidth&&((h=document.elementFromPoint(Math.round(a+.5),Math.round(d+.5)))===this.collectedLinks[e].e||h&&this.collectedLinks[e].e.contains(h)||this.collectedLinks[e].e.setAttribute("__fireshotHiddenLink",1))}},clearAttributes:function(){for(var a=k.getElementsByTagName("a"),d=0;d<a.length;++d)a[d].removeAttribute("__fireshotHiddenLink"),
a[d].removeAttribute("__fireshotLinkId")}}};
